### ISSUE TITLE
Import_data.py patching is not functional

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/fourfront#188]
patching is not working.
To patch data, I changed the field aliases to alias. (one can also use uuid or accession)

I prepared an example "fieldsRaoPatch.xls" that tries to change the definition of one of the experiment sets.
I run the command `python3 import_data.py Rao_et_al_2014/fieldsRaoPatch.xls --patchall`

and get the following error
```
koray@TecRef-LT-E49055:~/github/4DNWranglerTools/4DNScripts$ python3 import_data.py Rao_et_al_2014/fieldsRaoPatch.xls --patchall
Running on http://4dn-web-dev.us-east-1.elasticbeanstalk.com/
addedbykoray
http://4dn-web-dev.us-east-1.elasticbeanstalk.com/profiles/?limit=all&frame=object
addedbykoray
{'alias': 'dcic:rao23', 'description': 'Rao et al 2014, HiC Key Publication'}
Traceback (most recent call last):
  File "import_data.py", line 433, in <module>
    main()
  File "import_data.py", line 428, in main
    excel_reader(args.infile, n, args.update, connection, args.patchall)
  File "import_data.py", line 328, in excel_reader
    temp = encodedcc.get_ENCODE(post_json["alias"], connection)
  File "/Users/koray/Github/4DNWranglerTools/4DNScripts/encodedccMod.py", line 251, in get_ENCODE
    response = requests.get(url, auth=connection.auth, headers=connection.headers)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 579, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 653, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'dcic:rao23?limit=all&frame=object'
```

**Comment by j1z0** [comment]
ok this is now fixed in the Wrangler repo but you can continue to use aliases (it will pick the first on in the array) don't change to alias.
